pipeline:
  name: Demo for Kroger
  identifier: Demo_for_Kroger
  projectIdentifier: KD_Git_Ex
  orgIdentifier: KD
  tags: {}
  stages:
    - stage:
        name: Approval
        identifier: Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Echo
                  identifier: Echo
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello from the Feature-2 branch"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Approval
                  identifier: Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.Approvers
                    approverInputs: []
        tags: {}
